image: Visual Studio 2019
configuration: Release
platform: "Any CPU"

install:
  - git submodule update --init --recursive
  - choco install gitversion.portable -y

before_build:
  - ps: gitversion /l console /output buildserver
  - ps: $env:PackageVersion=$env:GitVersion_NuGetVersion
  - ps: $env:AssemblyVersion=$env:GitVersion_AssemblySemVer
  - ps: $env:FileVersion=$env:GitVersion_MajorMinorPatch.0
  - ps: $env:InformationalVersion=$env:GitVersion_InformationalVersion
  - ps: $env:PackageOutputPath="$env:APPVEYOR_BUILD_FOLDER\pkg"
  - wsl sudo apt-get -y install g++ gdb make ninja-build rsync zip clang
  - cmake -S src\boolexpr32 -B src\boolexpr32 -G "Visual Studio 16 2019" -A Win32
  - cmake -S src\boolexpr64 -B src\boolexpr64 -G "Visual Studio 16 2019" -A x64
  - msbuild src\BoolExprNet.sln /t:Restore
  
build:
  project: src\BoolExprNet.sln
  parallel: true
  verbosity: minimal

artifacts:
  - path: pkg\*.nupkg
    name: BoolExprNet

deploy:
  - provider: NuGet
    server: https://nuget.pkg.github.com/alethic/index.json
    username: wasabii
    api_key:
      secure: u7+1z/CZGBli+CiDxHSQetMjE1dbaf1f9eJtSCb8wifl7s1+AdnhWjnsjGQaEsAw
    skip_symbols: false
    symbol_server:
    artifact: /.*\.nupkg/