image: Visual Studio 2019
configuration: Release
platform: "Any CPU"

install:
  - git submodule update --init --recursive
  - choco install gitversion.portable -y

before_build:
  - ps: gitversion /l console /output buildserver
  - ps: $env:PackageVersion=$env:GitVersion_NuGetVersion
  - ps: $env:AssemblyVersion=$env:GitVersion_AssemblySemVer
  - ps: $env:FileVersion=$env:GitVersion_MajorMinorPatch.0
  - ps: $env:InformationalVersion=$env:GitVersion_InformationalVersion
  - ps: $env:PackageOutputPath="$env:APPVEYOR_BUILD_FOLDER\pkg"
  - cd src\boolexpr32 && cmake -G "Visual Studio 16 2019" -A Win32 .
  - cd src\boolexpr64 && cmake -G "Visual Studio 16 2019" -A x64 .
  - msbuild src\BoolExprNet.sln /t:Restore
  
build:
  verbosity: minimal
  project: src\BoolExprNet.sln

artifacts:
  - path: pkg\*.nupkg
    name: BoolExprNet

deploy:
  provider: NuGet
  server: https://nuget.pkg.github.com/wasabii/index.json
  username: wasabii
  api_key:
    secure: xrFuWmVqekabWUvYce7mOmKS4ToqdtFJOGgiLYyrDRVZJhMSMvpOUVxf0mhzwGiH
  skip_symbols: false
  symbol_server:
  artifact: /.*\.nupkg/
