image: Visual Studio 2017
configuration: Release
platform: Any CPU

install:
  - git submodule update --init --recursive
  - choco install gitversion.portable -pre -y

before_build:
  - pushd src\boolexpr32; "%DevEnvDir%\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -G "Visual Studio 15 2017" ; popd
  - pushd src\boolexpr64; "%DevEnvDir%\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -G "Visual Studio 15 2017 Win64"; popd
  - ps: gitversion /l console /output buildserver
  - ps: $env:PackageVersion=$env:GitVersion_NuGetVersion
  - ps: $env:AssemblyVersion=$env:GitVersion_AssemblySemVer
  - ps: $env:FileVersion=$env:GitVersion_MajorMinorPatch.0
  - ps: $env:InformationalVersion=$env:GitVersion_InformationalVersion
  - ps: $env:PackageOutputPath="$env:APPVEYOR_BUILD_FOLDER\pkg"
  - nuget restore src/BoolExprNet.sln
  - dotnet restore src/BoolExprNet.sln

build:
  verbosity: minimal
  project: src/BoolExprNet.sln

artifacts:
  - path: pkg/*.nupkg
    name: BoolExprNet
